---
- name: publish all new content views
  hosts: Satellite
  gather_facts: false
  tasks:
  - name: update all content views
    shell: "./cvmanager --config={{ item }}.yml --wait promote"
    args:
      chdir: /katello-cvmanager/
    with_items:
      - "{{ lifecycle }}"
