---
- name: publish all new content views
  hosts: Satellite
  tasks:
  - name: update all content views
    shell: ./cvmanager --config=publish.yml --wait publish
    args:
      chdir: /katello-cvmanager/
