- name: Patch RHEL Servers
  hosts: RHEL
  tasks:
    - name: Ensure Yum-utils is installed
      yum:
        name: yum-utils
        state: present

    - name: check for updates (yum)
      yum: 
        list: updates 
        update_cache: true
      register: yum_updates

    - block:
        - name: upgrade all packages
          yum: 
            name: '*' 
            state: latest


